{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bun-cron-chart.serviceAccountName" . }}
  labels: {{- include "bun-cron-chart.labels" . | nindent 4 }}
  annotations: {{- include "bun-cron-chart.annotations" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
