version: '3.7'

services:
  consumer:
    build: .
    command: watch -d 28-12-2023 -i 5 -f JToW
    volumes:
      - ./config:/app/config
  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - '6379:6379'
    ulimits:
      memlock: -1
    environment:
      DFLY_requirepass: supersecret
