apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "root-chart.fullname-with-suffix" (dict "arg" "config" "root" .) }}
  labels: {{- include "root-chart.labels" . | nindent 4 }}
  annotations: {{- include "root-chart.annotations" . | nindent 4 }}
data:
  {{ .Values.serviceTree.landscape }}.config.yaml: |
    {{- $path := printf "%s%s.config.yaml" "app/" .Values.serviceTree.landscape -}}
    {{- $fileContent := .Files.Get $path -}}
    {{- $config := fromYaml $fileContent -}}
    {{- $final := deepCopy $config | merge (deepCopy .Values.appSettings)  -}}
    {{- toYaml $final | nindent 4 }}
