serviceTree:
  landscape: lapras
  platform: nitroso
  service: helium
  module: scheduler

schedule: "@midnight"

appSettings: {}

annotations: {}

envFromSecret: nitroso-helium

configMountPath: /app/config/app

image:
  repository: nitroso-helium-scheduler
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: {}

restartPolicy: Never
