apiVersion: v2
name: root-chart
description: Root Chart to a single Service

type: application
version: 0.1.0
appVersion: '1.16.0'

dependencies:
  - name: sulfoxide-bromine
    version: 1.6.0
    condition: bromine.enable
    alias: bromine
    repository: oci://ghcr.io/atomicloud/sulfoxide.bromine
  - name: root-chart
    version: 1.26.0
    condition: zinc.enable
    alias: zinc
    repository: oci://ghcr.io/atomicloud/nitroso.zinc
  - name: bun-cron-chart
    version: 0.1.0
    repository: file://../cron_chart
    alias: scheduler
    condition: scheduler.enabled
  - name: bun-cron-chart
    version: 0.1.0
    repository: file://../cron_chart
    alias: refunder
    condition: refunder.enabled
  - name: bun-cron-chart
    version: 0.1.0
    repository: file://../cron_chart
    alias: reverter
    condition: reverter.enabled
