serviceTree:
  landscape: &landscape lapras

bromine:
  enable: true

zinc:
  enable: true
  serviceTree:
    landscape: *landscape
  bromine:
    enable: true
  api:
    enabled: true
    replicaCount: 1
    configMountPath: /app/Config
    fullnameOverride: "zinc-api"
    appSettings:
      Database:
        MAIN:
          AutoMigrate: true
    service:
      type: ClusterIP
      port: 80
      containerPort: 9001
    serviceTree:
      landscape: *landscape
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: api.zinc.nitroso.lapras.lvh.me
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  migration:
    enabled: false
  maincache:
    enable: true
    fullnameOverride: "zinc-maincache"
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "250m"
  maindb:
    enable: true
    fullnameOverride: "zinc-maindb"
  mainstorage:
    enable: true
    fullnameOverride: "zinc-mainstorage"

scheduler:
  schedule: "02 12 * * *"
  fullnameOverride: "helium-scheduler"
  serviceTree:
    landscape: *landscape
