serviceTree: &serviceTree
  landscape: lapras
  platform: nitroso
  service: &service helium
  module: pollee
  layer: '2'

bromine:
  serviceTree:
    <<: *serviceTree
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  enable: true
  # -- Store name to create
  storeName: *service
  # -- Secret of Secrets reference
  rootSecret:
    name: *service
    # -- Infisical Token Reference
    ref:
      clientId: NITROSO_HELIUM_CLIENT_ID
      clientSecret: NITROSO_HELIUM_CLIENT_SECRET

  target: &target helium

appSettings: {}

zinc:
  api:
    configMountPath: /app/Config
    image:
      repository: ghcr.io/atomicloud/nitroso.zinc/api

  migration:
    enabled: false

scheduler:
  serviceTree:
    <<: *serviceTree
    module: scheduler

  schedule: '0 16 * * *'
  command:
    - 'bun'
    - 'run'
    - 'index.js'
    - 'schedule'

  restartPolicy: 'Never'

  envFromSecret: *target

refunder:
  serviceTree:
    <<: *serviceTree
    module: refunder

  schedule: '30 5-23 * * *'
  timeZone: 'Asia/Singapore'
  command:
    - 'bun'
    - 'run'
    - 'index.js'
    - 'refunder'

  restartPolicy: 'Never'

  envFromSecret: *target

reverter:
  serviceTree:
    <<: *serviceTree
    module: reverter

  schedule: '*/5 * * * *'
  timeZone: 'Asia/Singapore'
  command:
    - 'bun'
    - 'run'
    - 'index.js'
    - 'reverter'

  restartPolicy: 'Never'

  envFromSecret: *target
