serviceTree: &serviceTree
  landscape: lapras
  platform: nitroso
  service: helium
  module: pollee
  layer: "2"

bromine:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  enable: true
  # -- Store name to create
  storeName: nitroso-helium
  # -- Secret of Secrets reference
  rootSecret:
    # -- DOPPLER Token Reference
    ref: "NITROSO_HELIUM"

    name: "nitroso-helium-doppler"

  target: &target "nitroso-helium"

appSettings: {}

zinc:
  api:
    configMountPath: /app/Config
    image:
      repository: ghcr.io/atomicloud/nitroso.zinc/api-arm

  migration:
    enabled: false

scheduler:
  serviceTree:
    <<: *serviceTree
    module: scheduler

  schedule: "0 16 * * *"
  command:
    - "bun"
    - "run"
    - "index.js"
    - "schedule"

  restartPolicy: "Never"

  envFromSecret: *target
