serviceTree:
  landscape: &landscape pikachu

# -- YAML Anchor for PodSecurityContext
podSecurityContext: &podSecurityContext
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

# -- YAML Anchor for SecurityContext
securityContext: &securityContext
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL

bromine:
  enable: true
  serviceTree:
    landscape: *landscape

fullnameOverride: "helium-pollee"

zinc:
  enable: false

scheduler:
  enable: true
  image:
    repository: ghcr.io/atomicloud/nitroso.helium/nitroso-helium
  serviceTree:
    landscape: *landscape
  fullnameOverride: "helium-scheduler"
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "250m"

refunder:
  enable: true
  image:
    repository: ghcr.io/atomicloud/nitroso.helium/nitroso-helium
  serviceTree:
    landscape: *landscape
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  fullnameOverride: "helium-refunder"
  resources:
    requests:
      memory: "5Mi"
      cpu: "5m"
    limits:
      memory: "128Mi"
      cpu: "125m"

reverter:
  enable: true
  schedule: "0 0 * * 0"
  image:
    repository: ghcr.io/atomicloud/nitroso.helium/nitroso-helium
  serviceTree:
    landscape: *landscape
  securityContext: *securityContext
  podSecurityContext: *podSecurityContext
  fullnameOverride: "helium-reverter"
  resources:
    requests:
      memory: "5Mi"
      cpu: "5m"
    limits:
      memory: "128Mi"
      cpu: "125m"
