# yaml-language-server: $schema=./schema.json
$schema: ./schema.json

app:
  landscape: pikachu
  populator:
    delay: 0.5
  watcher:
    delay: 1
cache:
  live:
    endpoints:
      0: tin-livecache-master:6379
    tls: false

auth:
  descope:
    id: 'P2Z1CwarRwCS3WymAQ2js94dnmbo'
    key: ''

otel:
  logging:
    enabled: true
    level: info
    prettify: false
    safe: true
  metrics:
    exporter:
      interval: 1000
      use: otlp
      otlp:
        compression: gzip
        headers: {}
        timeout: 3000
        url: 'http://silicon-otlp-collector.sulfoxide.svc:4318'
  trace:
    exporter:
      use: otlp
      otlp:
        compression: gzip
        headers: {}
        timeout: 3000
        url: 'http://silicon-otlp-collector.sulfoxide.svc:4318'
